apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    # Dette er den magiske delen som tillater privileged pods i dette namespacet
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged