apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 10m
  chart:
    spec:
      chart: authentik
      version: "2024.2.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
  values:
    authentik:
      secret_key: "veldig-hemmelig-nøkkel-bytt-meg-ut-senere" 
    
    # Disse må ligge her ute!
    postgresql:
      enabled: false 

    redis:
      enabled: true
      architecture: standalone
    
    global:
      env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: username
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: password

    server:
      ingress:
        enabled: true
        ingressClassName: haproxy
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - auth.hammers.no
        paths:
          - /
        pathType: Prefix
        tls:
          - secretName: auth-hammers-no-tls
            hosts:
              - auth.hammers.no