apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-db
  namespace: gitlab
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 15Gi
  
  # Dette er nøkkelen for at migrasjoner skal fungere med CNPG
  enableSuperuserAccess: true 

  bootstrap:
    initdb:
      database: gitlab
      owner: gitlab
      # Installer utvidelsene GitLab krever
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS btree_gist;
        - CREATE EXTENSION IF NOT EXISTS plpgsql;