apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-db
  namespace: gitlab
spec:
  instances: 2
  storage:
    storageClass: longhorn
    size: 15Gi
  # Dette gir operatøren lov til å fikse ting som krever høye rettigheter
  enableSuperuserAccess: true 
  bootstrap:
    initdb:
      database: gitlab
      owner: gitlab