apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 10m
  timeout: 30m
  chart:
    spec:
      chart: gitlab
      version: "9.9.x"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      edition: ce
      hosts:
        domain: hammers.no
      ingress:
        configureCertmanager: false
        class: haproxy
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
      
      # --- EKSTERN DATABASE (CNPG) ---
      psql:
        host: gitlab-db-rw # Tjenesten CNPG oppretter
        port: 5432
        username: gitlab
        database: gitlab
        password:
          secret: gitlab-db-app # Secret CNPG oppretter automatisk
          key: password
          
    # --- DEAKTIVER INNEBYGDE TING ---
    installCertmanager: false
    certmanager:
      installCRDs: false
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    gitlab-runner:
      install: false
      
    # Slå av GitLabs egen PostgreSQL!
    postgresql:
      install: false

# --- LAGRING (Longhorn) ---
    redis:
      architecture: standalone
      # Fortell den at den må hente fra arkivet:
      image:
        repository: bitnamilegacy/redis
      metrics:
        image:
          repository: bitnamilegacy/redis-exporter
      master:
        persistence:
          storageClass: "longhorn"
          size: 2Gi
    minio:
      persistence:
        storageClass: "longhorn"
        size: 10Gi
    gitlab:
      gitaly:
        persistence:
          storageClass: "longhorn"
          size: 10Gi
      # --- NY SEKSJON STARTER HER ---
      webservice:
        resources:
          requests:
            cpu: 1000m      # Vi dobler kravet
            memory: 3Gi      # Vi øker minimum RAM
          limits:
            cpu: 4000m       # Gir den 4 kjerner til rådighet under oppstart
            memory: 5Gi      # Gir den mer pusterom på RAM
        livenessProbe:
          initialDelaySeconds: 600
          periodSeconds: 30
          failureThreshold: 20
        readinessProbe:
          initialDelaySeconds: 300
          periodSeconds: 15
          failureThreshold: 30
      sidekiq:
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi