apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: "v1.15.x" # Bruker en ny og stabil versjon
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Veldig viktig for cert-manager: Den må få lov til å installere CRD-ene sine
    crds:
      enabled: true