apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy
  namespace: haproxy-ingress
spec:
  interval: 10m
  chart:
    spec:
      chart: kubernetes-ingress
      version: ">=1.30.0" # Henter en ny og stabil versjon
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: haproxy-ingress
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    controller:
      replicaCount: 3
      service:
        type: LoadBalancer