apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-console
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: rcon-web-admin
      version: "1.1.0" # Fra Chart.yaml
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: minecraft
  values:
    image:
      repository: docker.io/itzg/rcon # Riktig image fra itzg
    
    rconWeb:
      rconHost: "minecraft" # Navnet p책 din minecraft-service
      rconPassword: "minecraft" # M책 matche passordet i din minecraft helm-release
      password: "admin" # Dette er passordet for 책 logge inn p책 web-siden
      game: minecraft
    
    ingress:
      enabled: true
      className: "haproxy" # Samme som authentik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      host: mc.hammers.no
      tls:
        - secretName: mc-console-tls
          hosts:
            - mc.hammers.no