apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-console
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: rcon-web-admin
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: minecraft
  values:
    image:
      repository: docker.io/itzg/rcon
    
    rconWeb:
      # ENDRE DENNE LINJEN:
      rconHost: "minecraft-rcon" # Peik på rcon-servicen
      rconPort: 25575 # Standard RCON-port
      rconPassword: "minecraft" 
      password: "admin" 
      game: minecraft
    
    ingress:
      enabled: true
      className: "haproxy"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      host: mc.hammers.no
      tls:
        - secretName: mc-console-tls
          hosts:
            - mc.hammers.no