apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: minecraft
  values:
    minecraftServer:
      eula: true
      version: "LATEST"
      type: "PAPER"
      difficulty: "easy"
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    service:
      type: LoadBalancer
      port: 25565
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 4Gi