apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 10m
  chart:
    spec:
      chart: minecraft
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: minecraft
  values:
    minecraftServer:
      eula: true
      version: "LATEST"
      type: "PAPER" # Anbefalt for ytelse og plugins, kan endres til "VANILLA"
      difficulty: "easy"
    
    # Bruker Longhorn for å lagre verdenen din, slik som authentik-db
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 10Gi

    # Siden Minecraft bruker TCP, eksponerer vi det via LoadBalancer (MetalLB)
    service:
      type: LoadBalancer
      port: 25565
    
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 4Gi